### ISSUE TITLE
Collect latest cards data

### ISSUE THREAD

**Issue by synasius** [evonove/mysthea-app#74]
We need the latest cards data:
- codes
- images (see #82)
- descriptions with translations in all the languages (see below)

Needed Translation:
- [x] English
- [x] Italian
- [x] German
- [x] Japanese
- [x] French 
- [x] Spanish

**Comment by synasius** [comment]
Upadted Cards Data can be found here:
https://docs.google.com/spreadsheets/d/1qJ0bjb5dBBqfXAzqU3IUZ_qgmQNc4YYMqYnSa0ptoI0/edit#gid=0

**Comment by synasius** [comment]
For faster reference I uploaded the available translation + the main english reference here

[App Cards File.xlsx](https://github.com/evonove/mysthea-app/files/2732335/App.Cards.File.xlsx)
[App Cards File German.xlsx](https://github.com/evonove/mysthea-app/files/2732336/App.Cards.File.German.xlsx)
[App Cards File ITALIAN.xlsx](https://github.com/evonove/mysthea-app/files/2732337/App.Cards.File.ITALIAN.xlsx)
[App Cards File JPN.xlsx](https://github.com/evonove/mysthea-app/files/2732338/App.Cards.File.JPN.xlsx)

@Alien1993 Can you double check the files??

**Comment by silvanocerza** [comment]
[App Cards File French.xlsx](https://github.com/evonove/mysthea-app/files/2737671/App.Cards.File.French.xlsx)
[App Cards File Spanish.xlsx](https://github.com/evonove/mysthea-app/files/2737672/App.Cards.File.Spanish.xlsx)
